### ISSUE TITLE
Filter html output based on Exomiser score

### ISSUE THREAD

**Issue by oleraj** [exomiser/Exomiser#365]
Hi,

I've been playing around with Exomiser a bit and trying to find a way to filter in different ways.  I can't seem to be able to find a way to say only report genes with Exomiser score > 0.8 for example.  I've tried using `priorityScoreFilter` but it seems I can only use that with Phenotype scores (?) like hiPhive and others.  Any way to filter on Exomiser score directly using the yml file?

Thanks,

Andrew

**Comment by julesjacobsen** [comment]
Hi Andrew, Sorry this isn't possible right now, but it does seem like a rather obvious thing to want to do! Usually we report the top ~3-5 scores as this is where we found the majority of the hits in agreement with manually solved cases in our benchmarking. This can be set using:

```yml
outputOptions:
    #numGenes options: 0 = all or specify a limit e.g. 500 for the first 500 results  
    numGenes: 0
```

@damiansm what do you think? Worth adding an Exomiser score filter to the `outputOptions`?
