### ISSUE TITLE
Create new input parameters for CLI to enable phenopacket and preset specification

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#372]
Related to #369, #370, #371 

New CLI options
=
Allowable CLI input options should be:

```bash
--analysis path/to/file
--analysis-batch path/to/file
--sample path/to/file
--preset [EXOME/GENOME]
--output path/to/file
```

The existing `analysis.yml` will be split into three sections:

Sample
=
This can be one of a new Sample object, Phenopacket or Family
```yml
---
genomeAssembly: hg19
vcf: "examples/Pfeiffer.vcf"
ped: "examples/Pfeiffer-singleton.ped"
proband: "manuel"
hpoIds:
- "HP:0001156"
- "HP:0001363"
- "HP:0011304"
- "HP:0010055"
```

Analysis
=
This is now a subset of the top-half of the original analysis.yml

```yaml
---
analysisMode: PASS_ONLY
inheritanceModes: {
    AUTOSOMAL_DOMINANT: 0.1,
    AUTOSOMAL_RECESSIVE_COMP_HET: 2.0,
    AUTOSOMAL_RECESSIVE_HOM_ALT: 0.1,
    X_DOMINANT: 0.1,
    X_RECESSIVE_COMP_HET: 2.0,
    X_RECESSIVE_HOM_ALT: 0.1,
    MITOCHONDRIAL: 0.2
}
frequencySources: [
    THOUSAND_GENOMES,
    TOPMED,
    UK10K,

    ESP_AFRICAN_AMERICAN, ESP_EUROPEAN_AMERICAN, ESP_ALL,

    EXAC_AFRICAN_INC_AFRICAN_AMERICAN, EXAC_AMERICAN,
    EXAC_SOUTH_ASIAN, EXAC_EAST_ASIAN,
    EXAC_FINNISH, EXAC_NON_FINNISH_EUROPEAN,
    EXAC_OTHER,

    GNOMAD_E_AFR,
    GNOMAD_E_AMR,
#        GNOMAD_E_ASJ,
    GNOMAD_E_EAS,
    GNOMAD_E_FIN,
    GNOMAD_E_NFE,
    GNOMAD_E_OTH,
    GNOMAD_E_SAS,

    GNOMAD_G_AFR,
    GNOMAD_G_AMR,
#        GNOMAD_G_ASJ,
    GNOMAD_G_EAS,
    GNOMAD_G_FIN,
    GNOMAD_G_NFE,
    GNOMAD_G_OTH,
    GNOMAD_G_SAS
]
pathogenicitySources: [POLYPHEN, MUTATION_TASTER, SIFT]
#this is the standard exomiser order.
steps: [
    variantEffectFilter: {
        remove: [
            FIVE_PRIME_UTR_EXON_VARIANT,
            FIVE_PRIME_UTR_INTRON_VARIANT,
            THREE_PRIME_UTR_EXON_VARIANT,
            THREE_PRIME_UTR_INTRON_VARIANT,
            NON_CODING_TRANSCRIPT_EXON_VARIANT,
            UPSTREAM_GENE_VARIANT,
            INTERGENIC_VARIANT,
            REGULATORY_REGION_VARIANT,
            CODING_TRANSCRIPT_INTRON_VARIANT,
            NON_CODING_TRANSCRIPT_INTRON_VARIANT,
            DOWNSTREAM_GENE_VARIANT
        ]
    },
    frequencyFilter: {maxFrequency: 2.0},
    pathogenicityFilter: {keepNonPathogenic: true},
    inheritanceFilter: {},
    omimPrioritiser: {},
    hiPhivePrioritiser: {}
]
```

- The `--analysis` option should be backwards-compatible with the existing analysis.yml
- The `--analysis` option should be able to accept the new `job` format (see below)
- The `--analysis` option should be able to accept the new analysis object along with a combination of the `--sample` and `--output`
- The `--analysis` option should _not_ be allowed with the `--preset` option
- If missing the analysis should default to the `--preset EXOME` option

Preset
=
- The `--preset` option should *not* be allowed with the `--analysis` option
- The `--preset` option must be one of `EXOME` or `GENOME`
- If missing the preset value should default to `EXOME`

Output
=
The is the same as the old outputOptions in the existing analysis.yml
```yml
---
outputContributingVariantsOnly: false
numGenes: 0
outputPrefix: results/Pfeiffer-hiphive-exome
outputFormats: [HTML, JSON, TSV_GENE, TSV_VARIANT, VCF]
```
- If missing the default formats will be JSON and HTML
- If missing the default outputPrefix could be empty or ideally the sample _filename_

Job
=
It should be possible to specify any of the above in a single job. This is analogous to the existing `analysis.yml`, however should support presets and alternative sample input formats. For example the above options run using the exome preset will look like this:

```yml
---
sample:
    genomeAssembly: hg19
    vcf: examples/Pfeiffer.vcf
    ped: examples/Pfeiffer-singleton.ped
    proband: manuel
    hpoIds: ['HP:0001156', 'HP:0001363', 'HP:0011304', 'HP:0010055']
preset: EXOME
outputOptions:
    outputContributingVariantsOnly: false
    numGenes: 0
    outputPrefix: results/Pfeiffer-hiphive-exome
    outputFormats: [HTML, JSON, TSV_GENE, TSV_VARIANT, VCF]
```
