### ISSUE TITLE
Appropriate variants are filtered out

### ISSUE THREAD

**Issue by hongsilv** [exomiser/Exomiser#386]
Hi. This is Sungeun.
Thank you for the great software!

While using exomiser, I realized that some variants are filtered out, even though I know that they pass the variant filters.
For example, vcf rows with following variant are present in the input vcf files, 
and I know they are coding region, nonsynonymous SNPs, 
and their allele frequency is below 0.1% . (+ I didn't set any inheritance filters for exomiser analysis)
But when I run the exomiser, they are not present in the output vcf.

I tried two approaches such: 
1) remove all variant filters in analysis yml file (except the AF filter)-> still they are gone
2) subset input vcf to include regions near SNP (10kb ~ 100kb), and run exomiser on that smaller input vcf -> SNPs nearby are all together filtered out.

Do you have any idea why are these variants filtered out, and how I can solve this?

**(HG 19, rs146768859)**
chr4 | 186456560 | . | G | A | 46780.9 | PASS | AC=2;AF=0.03;AN=2;AS_BaseQRankSum=6.671;AS_FS=1.396;AS_InbreedingCoeff=0.3761;AS_MQ=60;AS_MQRankSum=0;AS_QD=18.95;AS_ReadPosRankSum=0.857;AS_SOR=0.619;BaseQRankSum=3.22;DP=24846;ExcessHet=0.1353;FS=1.396;InbreedingCoeff=0.3761;MLEAC=5;MLEAF=0.03;MQ=60;MQRankSum=0;QD=18.95;ReadPosRankSum=0.095;SOR=0.619 | GT:AD:DP:GQ:PL | 1/1:0,862:.:99:25451,2579,0

**(HG19, rs141509078)**
chr15 | 72191053 | . | T | G | 1002.01 | PASS | AC=2;AF=0.018;AN=2;AS_BaseQRankSum=-1.055;AS_FS=0;AS_InbreedingCoeff=0.6493;AS_MQ=60;AS_MQRankSum=0;AS_QD=24.44;AS_ReadPosRankSum=-1.068;AS_SOR=0.968;BaseQRankSum=-1.019;DP=2402;ExcessHet=0.0402;FS=0;InbreedingCoeff=0.6493;MLEAC=3;MLEAF=0.018;MQ=60;MQRankSum=0;QD=24.44;ReadPosRankSum=-0.957;SOR=0.968 | GT:AD:DP:GQ:PL | 1/1:0,27:.:81:778,81,0

**(Example of my yml file)**
```
analysis:
  analysisMode: PASS_ONLY
  frequencySources:
  - THOUSAND_GENOMES
  - TOPMED
  - UK10K
  - ESP_AFRICAN_AMERICAN
  - ESP_EUROPEAN_AMERICAN
  - ESP_ALL
  - EXAC_AFRICAN_INC_AFRICAN_AMERICAN
  - EXAC_AMERICAN
  - EXAC_SOUTH_ASIAN
  - EXAC_EAST_ASIAN
  - EXAC_FINNISH
  - EXAC_NON_FINNISH_EUROPEAN
  - EXAC_OTHER
  - GNOMAD_E_AFR
  - GNOMAD_E_AMR
  - GNOMAD_E_EAS
  - GNOMAD_E_FIN
  - GNOMAD_E_NFE
  - GNOMAD_E_OTH
  - GNOMAD_E_SAS
  - GNOMAD_G_AFR
  - GNOMAD_G_AMR
  - GNOMAD_G_EAS
  - GNOMAD_G_FIN
  - GNOMAD_G_NFE
  - GNOMAD_G_OTH
  - GNOMAD_G_SAS
  genomeAssembly: hg19
  hpoIds:
  - HP:0002515
  - HP:0030234
  - HP:0030319
  - HP:0030192
  - HP:0003693
  - HP:0003326
  - HP:0003560
  inheritanceModes: {}
  pathogenicitySources:
  - POLYPHEN
  - MUTATION_TASTER
  - SIFT
  ped: null
  proband: null
  steps:
  #- variantEffectFilter:
      #remove:
      #- FIVE_PRIME_UTR_EXON_VARIANT
      #- FIVE_PRIME_UTR_INTRON_VARIANT
      #- THREE_PRIME_UTR_EXON_VARIANT
      #- THREE_PRIME_UTR_INTRON_VARIANT
      #- NON_CODING_TRANSCRIPT_EXON_VARIANT
      #- UPSTREAM_GENE_VARIANT
      #- INTERGENIC_VARIANT
      #- REGULATORY_REGION_VARIANT
      #- CODING_TRANSCRIPT_INTRON_VARIANT
      #- NON_CODING_TRANSCRIPT_INTRON_VARIANT
      #- DOWNSTREAM_GENE_VARIANT
  - frequencyFilter:
      maxFrequency: 1.0
  - pathogenicityFilter:
      keepNonPathogenic: true
  - inheritanceFilter: {}
  - omimPrioritiser: {}
  - hiPhivePrioritiser: {}
  vcf: /Volumes/exomiser/sample.NoAnno.indelMax70.cov5.chr4.10kb.vcf
outputOptions:
  numGenes: 0
  outputContributingVariantsOnly: false
  outputFormats:
  - HTML
  - TSV_GENE
  - TSV_VARIANT
  - VCF
  outputPrefix: results/v4/analysis_sample_10kb

```
