### ISSUE TITLE
ACMG classifications

### ISSUE THREAD

**Issue by Wynandi** [exomiser/Exomiser#507]
I am using Exomiser to specifically look at AR inheritance mode prioritizations,
I noticed the ACMG classifications (and p-values) are only in the summary .tsv, would it be possible to get them
also in the individual inheritance mode .tsv files?

Thank you.

Br,
Victoria

**Comment by julesjacobsen** [comment]
Hi Victoria,

The individual inheritance files are currently deprecated and will be removed in v 14 

https://exomiser.readthedocs.io/en/latest/result_interpretation.html#interpreting-the-results

In other words, you'll need to use the newer, combined files. If you're only looking at AR inheritance modes, you can edit your analysis.yml to filter for AR MOI like this:

```yml
  inheritanceModes:
#    AUTOSOMAL_DOMINANT: 0.1
    AUTOSOMAL_RECESSIVE_COMP_HET: 2.0
    AUTOSOMAL_RECESSIVE_HOM_ALT: 0.1
#    MITOCHONDRIAL: 0.2
#    X_DOMINANT: 0.1
    X_RECESSIVE_COMP_HET: 2.0
    X_RECESSIVE_HOM_ALT: 0.1
```

Then the file will only contain AR.
