### ISSUE TITLE
gnomad FIN In The `YML` But Not In The `HTML` Output For Exomiser Reference Version 2502 and Exomiser CLI Version 14.1.0

### ISSUE THREAD

**Issue by yr542** [exomiser/Exomiser#598]
**Exomiser Reference Version:** 2502
**Exomiser CL Version:** 14.1.0

I have the `yml` prepared with the following:

```
 frequencySources:
    - UK10K
    - GNOMAD_E_AFR
    - GNOMAD_E_AMR
    - GNOMAD_E_ASJ
    - GNOMAD_E_EAS
    - GNOMAD_E_FIN
    - GNOMAD_E_NFE
    - GNOMAD_E_OTH
    - GNOMAD_E_SAS
    - GNOMAD_G_AFR
    - GNOMAD_G_AMR
    - GNOMAD_G_ASJ
    - GNOMAD_G_EAS
    - GNOMAD_G_FIN
    - GNOMAD_G_NFE
    - GNOMAD_G_SAS
    - GNOMAD_G_OTH
  pathogenicitySources:
    - REVEL
    - POLYPHEN
    - MUTATION_TASTER
    - MVP
    - ALPHA_MISSENSE
    - SIFT
    - SPLICE_AI
```

But after using the Exomiser CLI Version 14.1.0 only some of each show up in the html:

```
  frequencySources:
  - "THOUSAND_GENOMES"
  - "TOPMED"
  - "UK10K"
  - "ESP_AA"
  - "ESP_EA"
  - "ESP_ALL"
  - "EXAC_AFRICAN_INC_AFRICAN_AMERICAN"
  - "EXAC_AMERICAN"
  - "EXAC_EAST_ASIAN"
  - "EXAC_NON_FINNISH_EUROPEAN"
  - "EXAC_SOUTH_ASIAN"
  - "GNOMAD_E_AFR"
  - "GNOMAD_E_AMR"
  - "GNOMAD_E_EAS"
  - "GNOMAD_E_NFE"
  - "GNOMAD_E_SAS"
  - "GNOMAD_G_AFR"
  - "GNOMAD_G_AMR"
  - "GNOMAD_G_EAS"
  - "GNOMAD_G_NFE"
  - "GNOMAD_G_SAS"
  pathogenicitySources:
  - "REVEL"
  - "MVP"
  ```
Questions:

1) Why is this the case? 

* The spacing is the same as far as I can tell in the `yml`. I have edited the `yml` in VScode and done 2 runs to check. 

2) Which does it not include the FIN population in this case? 

Thank you for your time. Any guidance you have for this issue is much appreciated.

**Comment by julesjacobsen** [comment]
I am unable to replicate this. Are you certain you are looking at the correct output file? 

Running:

```
java -jar exomiser-cli-14.1.0.jar --sample examples/pfeiffer-phenopacket.yml --analysis examples/test-analysis.yml 
```

This is the full analysis.yml I used:

```
analysis:
  inheritanceModes:
    AUTOSOMAL_RECESSIVE_COMP_HET: 2.0
    MITOCHONDRIAL: 0.2
    AUTOSOMAL_RECESSIVE_HOM_ALT: 0.1
    X_DOMINANT: 0.1
    AUTOSOMAL_DOMINANT: 0.1
    X_RECESSIVE_COMP_HET: 2.0
    X_RECESSIVE_HOM_ALT: 0.1
  frequencySources:
    - UK10K
    - GNOMAD_E_AFR
    - GNOMAD_E_AMR
    - GNOMAD_E_ASJ
    - GNOMAD_E_EAS
    - GNOMAD_E_FIN
    - GNOMAD_E_NFE
    - GNOMAD_E_OTH
    - GNOMAD_E_SAS
    - GNOMAD_G_AFR
    - GNOMAD_G_AMR
    - GNOMAD_G_ASJ
    - GNOMAD_G_EAS
    - GNOMAD_G_FIN
    - GNOMAD_G_NFE
    - GNOMAD_G_SAS
    - GNOMAD_G_OTH
  pathogenicitySources:
    - REVEL
    - POLYPHEN
    - MUTATION_TASTER
    - MVP
    - ALPHA_MISSENSE
    - SIFT
    - SPLICE_AI
  steps:
    - failedVariantFilter: {}
    - variantEffectFilter:
        remove:
          - "CODING_TRANSCRIPT_INTRON_VARIANT"
          - "FIVE_PRIME_UTR_EXON_VARIANT"
          - "THREE_PRIME_UTR_EXON_VARIANT"
          - "FIVE_PRIME_UTR_INTRON_VARIANT"
          - "THREE_PRIME_UTR_INTRON_VARIANT"
          - "NON_CODING_TRANSCRIPT_EXON_VARIANT"
          - "NON_CODING_TRANSCRIPT_INTRON_VARIANT"
          - "UPSTREAM_GENE_VARIANT"
          - "DOWNSTREAM_GENE_VARIANT"
          - "INTERGENIC_VARIANT"
          - "REGULATORY_REGION_VARIANT"
    - frequencyFilter:
        maxFrequency: 2.0
    - pathogenicityFilter:
        keepNonPathogenic: true
    - inheritanceFilter: {}
    - omimPrioritiser: {}
    - hiPhivePrioritiser:
        runParams: "human, mouse, fish, ppi"
```

I get the results file `Pfeiffer-exomiser.html` with the analysis settings section:

```
---
sample:
  genomeAssembly: "hg19"
  vcf: "examples/Pfeiffer.vcf"
  proband: "manuel"
  hpoIds:
  - "HP:0001159"
  - "HP:0000486"
  - "HP:0000327"
  - "HP:0000520"
  - "HP:0000316"
  - "HP:0000244"
  pedigree:
    persons:
    - individualId: "manuel"
      sex: "MALE"
      affectedStatus: "AFFECTED"
  sex: "MALE"
  age: {}
analysis:
  inheritanceModes:
    AUTOSOMAL_RECESSIVE_COMP_HET: 2.0
    MITOCHONDRIAL: 0.2
    AUTOSOMAL_RECESSIVE_HOM_ALT: 0.1
    X_DOMINANT: 0.1
    AUTOSOMAL_DOMINANT: 0.1
    X_RECESSIVE_COMP_HET: 2.0
    X_RECESSIVE_HOM_ALT: 0.1
  frequencySources:
  - "UK10K"
  - "GNOMAD_E_AFR"
  - "GNOMAD_E_AMR"
  - "GNOMAD_E_ASJ"
  - "GNOMAD_E_EAS"
  - "GNOMAD_E_FIN"
  - "GNOMAD_E_NFE"
  - "GNOMAD_E_OTH"
  - "GNOMAD_E_SAS"
  - "GNOMAD_G_AFR"
  - "GNOMAD_G_AMR"
  - "GNOMAD_G_ASJ"
  - "GNOMAD_G_EAS"
  - "GNOMAD_G_FIN"
  - "GNOMAD_G_NFE"
  - "GNOMAD_G_OTH"
  - "GNOMAD_G_SAS"
  pathogenicitySources:
  - "POLYPHEN"
  - "MUTATION_TASTER"
  - "SIFT"
  - "REVEL"
  - "MVP"
  - "SPLICE_AI"
  - "ALPHA_MISSENSE"
  steps:
  - failedVariantFilter: {}
  - variantEffectFilter:
      remove:
      - "CODING_TRANSCRIPT_INTRON_VARIANT"
      - "FIVE_PRIME_UTR_EXON_VARIANT"
      - "THREE_PRIME_UTR_EXON_VARIANT"
      - "FIVE_PRIME_UTR_INTRON_VARIANT"
      - "THREE_PRIME_UTR_INTRON_VARIANT"
      - "NON_CODING_TRANSCRIPT_EXON_VARIANT"
      - "NON_CODING_TRANSCRIPT_INTRON_VARIANT"
      - "UPSTREAM_GENE_VARIANT"
      - "DOWNSTREAM_GENE_VARIANT"
      - "INTERGENIC_VARIANT"
      - "REGULATORY_REGION_VARIANT"
  - frequencyFilter:
      maxFrequency: 2.0
  - pathogenicityFilter:
      keepNonPathogenic: true
  - inheritanceFilter: {}
  - omimPrioritiser: {}
  - hiPhivePrioritiser:
      runParams: "human, mouse, fish, ppi"
outputOptions:
  outputFormats:
  - "HTML"
  - "JSON"
  outputDirectory: "results"
```

**Comment by julesjacobsen** [comment]
One observation. Do not use  "POLYPHEN" , "MUTATION_TASTER" and "SIFT" with the other pathogenicity predictors. They tend to over-predict pathogenicity compared to the newer ones like REVEL, MVP and AlphaMissense. That is what the comment in the example files was trying to convey with the use of parentheses:

```
# Possible pathogenicitySources: (POLYPHEN, MUTATION_TASTER, SIFT), (REVEL, MVP), CADD, REMM
```

**Comment by yr542** [comment]
@julesjacobsen  I did try 2 separate runs after this post because I did see the pathogenicity sources reccomendd limits. I did the following:

1) Polyphony, Mutation taster, Sift and SpliceAI
2) Revel, MVP, Alpha-Missense and SpliceAI

but in the `html` it says Revel and MVP only each time so it is indicative of issues reading the `yml`.

**Comment by yr542** [comment]
@julesjacobsen  I used your analysis section.

**Restrictions Placed On HPC And Samples:**

- I cannot share the actual sample name as it could be identifiable 
- I cannot share my paths on the HPC due to rules set by my HPC administrator 

**Type of VCF:**

- It is a merged vcf that was bgzipped
- It contains a trio (affected son and unaffected mater and pater.

I did the following.

For the `yml`:

```
# A v1 phenopacket describing family FAM-1
---
id: FAM1
proband:
  subject:
    id: FAM1-1
    sex: MALE
  phenotypicFeatures:
    - type:
        id: HP:0001249
        label: Intellectual disability
    - type:
        id: HP:0012758
        label: Neurodevelopmental delay
    - type:
        id: HP:0000750
        label: Delayed speech and language development
pedigree:
  persons:
    - individualId: FAM1-1
      paternalId: FAM1-3
      maternalId: FAM1-2
      sex: MALE
      affectedStatus: AFFECTED
    - individualId: FAM1-3
      sex: MALE
      affectedStatus: UNAFFECTED
    - individualId: FAM1-2
      sex: FEMALE
      affectedStatus: UNAFFECTED
htsFiles:
  - uri: /path/to/FAM1_Trio_Family___Merged.vcf.gz
    htsFormat: VCF
    genomeAssembly: GRCh38
metaData:
  created: '2025-04-25T10:00:00Z'
  createdBy: YaRa
  resources:
    - id: hp
      name: human phenotype ontology
      url: http://purl.obolibrary.org/obo/hp.owl
      version: hp/releases/2024-04-01
      namespacePrefix: HP
      iriPrefix: 'http://purl.obolibrary.org/obo/HP_'
  phenopacketSchemaVersion: 1.0
analysis:
  inheritanceModes:
    AUTOSOMAL_RECESSIVE_COMP_HET: 2.0
    MITOCHONDRIAL: 0.2
    AUTOSOMAL_RECESSIVE_HOM_ALT: 0.1
    X_DOMINANT: 0.1
    AUTOSOMAL_DOMINANT: 0.1
    X_RECESSIVE_COMP_HET: 2.0
    X_RECESSIVE_HOM_ALT: 0.1
  frequencySources:
  - "UK10K"
  - "GNOMAD_E_AFR"
  - "GNOMAD_E_AMR"
  - "GNOMAD_E_ASJ"
  - "GNOMAD_E_EAS"
  - "GNOMAD_E_FIN"
  - "GNOMAD_E_NFE"
  - "GNOMAD_E_OTH"
  - "GNOMAD_E_SAS"
  - "GNOMAD_G_AFR"
  - "GNOMAD_G_AMR"
  - "GNOMAD_G_ASJ"
  - "GNOMAD_G_EAS"
  - "GNOMAD_G_FIN"
  - "GNOMAD_G_NFE"
  - "GNOMAD_G_OTH"
  - "GNOMAD_G_SAS"
  pathogenicitySources:
  - "REVEL"
  - "MVP"
  - "SPLICE_AI"
  - "ALPHA_MISSENSE"
  steps:
  - failedVariantFilter: {}
  - variantEffectFilter:
      remove:
      - "CODING_TRANSCRIPT_INTRON_VARIANT"
      - "FIVE_PRIME_UTR_EXON_VARIANT"
      - "THREE_PRIME_UTR_EXON_VARIANT"
      - "FIVE_PRIME_UTR_INTRON_VARIANT"
      - "THREE_PRIME_UTR_INTRON_VARIANT"
      - "NON_CODING_TRANSCRIPT_EXON_VARIANT"
      - "NON_CODING_TRANSCRIPT_INTRON_VARIANT"
      - "UPSTREAM_GENE_VARIANT"
      - "DOWNSTREAM_GENE_VARIANT"
      - "INTERGENIC_VARIANT"
      - "REGULATORY_REGION_VARIANT"
  - frequencyFilter:
      maxFrequency: 2.0
  - pathogenicityFilter:
      keepNonPathogenic: true
  - inheritanceFilter: {}
  - omimPrioritiser: {}
  - hiPhivePrioritiser:
      runParams: "human, mouse, fish, ppi"
```

and an output `yml` specified separately:

```
---
outputContributingVariantsOnly: false
# Number of genes to report 0 is all
numGenes: 0

# Path to the desired output directory.
outputDirectory: /path/removed/due/to/HPC/rules/

# Filename prefix for the output files.
outputFileName: FAM-1_Outputs

# Output formats: HTML, JSON, TSV_GENE, TSV_VARIANT, VCF
outputFormats: [HTML,JSON,TSV_GENE,TSV_VARIANT,VCF]
```

and I also had a pedigree `.ped` file.

**My Command:**

```
exomiser \
  --sample "/path/to/phenopacket/yml" \
  --output "/path/to/output/yml" \
  --ped "path/to/my/pedigree/file" \
  --spring.config.location="path/to/application_properties" \
  --vcf "path/to/my/merged/vcf" \
  --assembly hg38 \
  --debug
```

exomiser is the command on my HPC that contains the execution line is used via a module. However, I still have the same issues.

**Issues:**

- The html output does not show gnomad FIN
- The pathogenicity sources only show up as REVEL and MVP.

This suggests that there is still something wrong how Exomiser is reading the `yml`. I am unsure of what to do in this case.
